//
//  CustomerScreenViewController.swift
//  MeTechApp
//
//  Created by MacOS on 20.04.2022.
//

import UIKit
import FirebaseAnalytics

enum PaymentType {
    case cash
    case credit
    case cancel
    
    var title: String {
        switch self {
        case .cash:
            return "Nakit"
        case .credit:
            return "Kredi Kartı"
        case .cancel:
            return "iptal"
        }
    }
}

class CustomerScreenViewController: UIViewController {
    
    // MARK: -- UI Items
    @IBOutlet weak var qrCodeImageView: UIImageView!
    @IBOutlet weak var payStateLabel: UILabel!
    
    @IBOutlet weak var formStackView: UIStackView!
    @IBOutlet weak var formTitleLabel: UILabel!
    

    var coreBManager: CoreBManager = CoreBManager.shared
    
    override func viewDidLoad() {
        super.viewDidLoad()
        self.qrCodeImageView.image = self.generateQRCode(from: ApplicationData.shared.uuid)
        self.didReceiveWrite()
    }
    
    func didReceiveWrite() {
        self.coreBManager.didReceiveWrite = { (text: String) -> Void in
            let textComponents = text.components(separatedBy: "/")
            let dataType: DataType = textComponents[1] == DataType.amount.key ? DataType.amount : DataType.text
            if dataType == .amount {
                self.qrCodeImageView.isHidden = true
                self.formStackView.isHidden = false
                self.formTitleLabel.text = "Ödeme Tutarı: \(textComponents.first ?? "")"
            }
        }
    }
    
    func resultAlertAction() {
        let alert = UIAlertController(title: "Teşekkürler", message: "Ana sayfaya yönlendiriliceksiniz.", preferredStyle: UIAlertController.Style.alert)
        alert.addAction(UIAlertAction(title: "Tamam", style: UIAlertAction.Style.default, handler: { _ in
            self.back()
        }))
        self.present(alert, animated: true, completion: nil)
    }
    
    
    // MARK: -- Actions
    
    @IBAction func backButtonAction(_ sender: UIButton) {
        self.back()
    }
    
    @IBAction func cancelOrderAction(_ sender: UIButton) {
        let text = "\(PaymentType.cancel.title)/\(DataType.text.key)"
        self.coreBManager.updateValue(text: text)
        self.resultAlertAction()
    }
    
    @IBAction func payCashAction(_ sender: UIButton) {
        let text = "\(PaymentType.cash.title)/\(DataType.text.key)"
        self.coreBManager.updateValue(text: text)
        self.resultAlertAction()
    }
    
    @IBAction func payWithCreditCardAction(_ sender: UIButton) {
        let text = "\(PaymentType.credit.title)/\(DataType.text.key)"
        self.coreBManager.updateValue(text: text)
        self.resultAlertAction()
    }
    
    @IBAction func crashReportAction(_ sender: UIButton) {
        fatalError()
    }
    
    
    // QR Code Generator
    func generateQRCode(from string: String) -> UIImage? {
        let data = string.data(using: String.Encoding.ascii)

        if let filter = CIFilter(name: "CIQRCodeGenerator") {
            filter.setValue(data, forKey: "inputMessage")
            let transform = CGAffineTransform(scaleX: 3, y: 3)

            if let output = filter.outputImage?.transformed(by: transform) {
                Analytics.logEvent("qr_code_generated", parameters: [
                  "name": "Customer" as NSObject,
                  "full_text": "Qr code generated by customer" as NSObject,
                ])
                return UIImage(ciImage: output)
            }
        }
        return nil
    }

}
